ALTER TABLE "UserPreference"
ADD COLUMN "textScale" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "highContrast" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "reducedMotion" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "UserPreference" ADD COLUMN "lastSeenAt" TIMESTAMP(3);
